<?php

namespace EC\NotepadBundle\Repository;

/**
 * NoteClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteClassRepository extends \Doctrine\ORM\EntityRepository
{
}
